name: Dart CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: format
        run: dartfmt -n --set-exit-if-changed .
      - name: analyzer
        run: dartanalyzer --fatal-warnings --fatal-infos .
      - name: Run tests
        run: pub run test
      - name: Collect coverage
        run: |
          pub global activate test_coverage
          pub global run test_coverage
      - uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
